services:
  nginx:    
    image: nginx:stable-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    volumes:
      - ./:/app      
      - /app/node_modules  
    environment:
      - NODE_ENV=development
      - MONGO_USER=tejsva
      - MONGO_PASSWORD=password
      - SESSION_SECRET=password
    command: npm run dev
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tejsva
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
