
services:
  node-app:
    container_name: node-app
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./:/app      
      - /app/node_modules  
    env_file:
      - ./.env
